[project]
name = "mlflow-k8s"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docx2txt>=0.9",
    "mlflow>=3.9.0",
    "pandas>=2.3.3",
    "pypdf>=6.7.0",
    "scikit-learn>=1.8.0",
    "unstructured>=0.18.31",
]
