---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-model-server
spec:
  selector:
    matchLabels:
      app: diabetes-model-server
  replicas: 1
  template:
    metadata:
      labels:
        app: diabetes-model-server
    spec:
      containers:
      - name: diabetes-model-server-mlflow
        image: jcheng919/mlflow-k8s-diabetes-datasets:1.0.1
        ports:
        - containerPort: 5001
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow.mlflow.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-model-server-svc
spec:
  selector:
    app: diabetes-model-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP